# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'tailwind_rails_scaffold'
  s.version = '0.1.6'

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ['Roger Heykoop']
  s.date = '2021-01-19'
  s.description = 'Tailwind Rails Scaffold generator for Rails 6.1'
  s.email = 'roger@heykoop.nl'
  s.extra_rdoc_files = ['LICENSE.txt', 'README.rdoc']

  s.homepage = 'http://github.com/rogerheykoop/tailwind_rails_scaffold'
  s.licenses = ['MPL']
  s.require_paths = ['lib']
  s.rubygems_version = '1.3.7'
  s.summary = 'Rogers Tailwind Rails Scaffold generator for Rails 6.1'

  s.files = Dir['{app,config,db,lib}/**/*'] + ['LICENSE.txt', 'Rakefile', 'README.rdoc']
  s.test_files = Dir['test/**/*']


end


